### ISSUE TITLE
upgrade datastax agent 6.1.3 to latest 6.1.5

### ISSUE THREAD

**Issue by artooro** [datastax/docker-images#10]
I'm trying to move my kubernetes cluster to use these docker images. One thing I noticed is that Opscenter is complaining that the version of the agent on the nodes it out of date.

Would probably be a good idea to update them to 6.1.5

**Comment by pedjak** [comment]
Fixed in #11 and the images are republished.

**Comment by artooro** [comment]
@pedjak I just pulled the latest image from store/datastax/dse-server:5.1.5 and the hash hasn't changed, it's still `18940ccb5dd2be610e2137260a1cc16fc379058c1d3c059de31ae7b9d6530497`
Is there some kind of delay if you republish the image? Or maybe it requires a new tag.

**Comment by roberd13** [comment]
@artooro Try to perform a pull again as the new image was just published about an hour ago.
