### ISSUE TITLE
Docker image not set to use UTF-8 locale

### ISSUE THREAD

**Issue by DavidBgxg** [datastax/docker-images#19]
The docker image runs on ubuntu which has a default locale of POSIX.  Cassandra by default uses UTF-8 encoded strings for text values.  If you try and save a UTF-8 text string with special characters (e.g. "üéâäàåçêëèïîìæÆôöòûùÿ¢£¥PƒáíóúñÑ¿¬½¼¡«»¦ßµ±°•·²€„…†‡ˆ‰Š‹Œ‘’“”–—˜™š›œŸ¨©®¯³´¸¹¾ÀÁÂÃÄÅÈÉËÌÍÎÏÐÒÓÔÕÖ×ØÙÚÛÜÝÞãðõ÷øüýþ") or other text such as arabic the string comes back jumbled.

**Comment by mariofts** [comment]
@DavidBgxg you can set a custom java parameter `-Dfile.encoding=UTF-8`, this will solve our problem.

**Comment by DavidBgxg** [comment]
@mariofts Are you suggesting that we add that as an option to the cassandra-env file?  Also shouldn't the underlying container have this specified anyways since the default encoding for text fields in C* is UTF-8?

**Comment by roberd13** [comment]
We are setting the default to UTF-8 in the next build.  you can also set this with the current env `LANG=`
