### ISSUE TITLE
image dse-base or store/datastax/dse-server not available

### ISSUE THREAD

**Issue by e050110** [datastax/docker-images#23]
Dear All,

I tried to load docker-compose but it appears that even after login on docker, the images are unable to be found.

Images:
dse-base
store/datastax/dse-server

ex
docker run -e DS_LICENSE=accept --name my-dse -d store/datastax/dse-server:5.1.5
-> answer unable to find image

**Comment by marcore86** [comment]
Hi,
same problem is here.

OS : Ubuntu 16.04
Docker version: 1.13.1 build 092CBA3

Have you guys got any news?

**Comment by roberd13** [comment]
Did you subscribe to the image on docker store? Each user  must subscribe to the image one time which is free. Visit the DataStax Docker Store, click Setup Instructions, fill out the form then login with the user you subscribe to the image with and you are able to pull the image

**Comment by e050110** [comment]
Hello All, 
I found the issue 6> Image for dse-server is not anymore on docker hub. 
Dockerfile has to be modified to download dse server tar file from DataStax with the DataStax Academy credentials (username / password) and then build up the dse-server image.
Working fine for me

**Comment by antonior0409** [comment]
Hi, I'm trying to run dse-server image executing this command
`docker run -e DS_LICENSE=accept --name dse-server -d datastax/dse-server`

After starting container, I'm able to intercat using bash but I'm unable to connect to exposed port from host and external ones

Executing netstat command I see that services ports are not listening too

Can you help me?

**Comment by roberd13** [comment]
@antonior0409 you will have to publish the exposed ports with -p <port>:<port>  if you want to connect on those ports.  Exposing a port just says that it listens on these ports but does not actually publish it.  See https://docs.docker.com/engine/reference/builder/#expose for more info
