### ISSUE TITLE
Install JCE Unlimited Strength

### ISSUE THREAD

**Issue by millerjp** [datastax/docker-images#25]
JCE Unlimited strength does not appear to be installed with the Oracle JDK as ciphers over 128bit are being downgraded

``WARN  [main] 2018-03-08 08:06:38,699  SSLFactory.java:221 - Filtering out [TLS_RSA_WITH_AES_256_CBC_SHA] as it isn't supported by the socket
``

**Comment by millerjp** [comment]
FYI https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/security/secJceInstall.html

**Comment by sboulkour** [comment]
Hi !

I too have the issue, trying to connect DSE Studio to my DSE cluster behind SSL :
`Cannot support TLS_RSA_WITH_AES_256_CBC_SHA with currently installed providers`

**Comment by roberd13** [comment]
This is a licensing issue.  Although future release contain the Unlimited JCE, the version we include with the image does not.  As a workaround, you can download the Unlimited JCE and  use the `docker cp` command to add it to your containers or clone this repo and build it into the Docker file.  

Note: With the release model Oracle has decided to take, we are evaluating options with packaging JDK in our Docker Images.
