### ISSUE TITLE
missing directories for spark - docker image fails with -k 

### ISSUE THREAD

**Issue by norim** [datastax/docker-images#3]
Hi guys,

can you add the directories to the Dockerfile please.
/var/lib/spark/rdd 
/var/lib/spark/worker

The docker didn't  start with -k option and throws exceptions regarding missing directories.

Thank you!
Negib

**Comment by schrepfler** [comment]
Created PR https://github.com/datastax/docker-images/pull/8

**Comment by roberd13** [comment]
A new image available in store that fixes this issue
