### ISSUE TITLE
remove VOLUME option from Dockerfile

### ISSUE THREAD

**Issue by ttaranov** [datastax/docker-images#31]
current Dockerfile for dse-server exposes VOLUME option with among others /var/lib location that contains data. 

This is preventing creating an extension of the base dse image (e.g FROM datastax/dse-server:5.1.10), loading it with test data (for example), committing dse node image, and reusing downstream in say local dev purposes. 

Since there is no way in docker to unset VOLUME directive in child containers, please remove VOLUME from the parent dse container Dockerfile definition and leave it up to child implementation to define volumes.

**Comment by pedjak** [comment]
We need to declare volumes in order to deliver performant data access.

Have you seen this: https://github.com/moby/moby/issues/6999#issuecomment-336828327 ? There are listed a few approaches that deliver the usecase you have described.

**Comment by ttaranov** [comment]
I ended up implementing something similar to what is in the comment - created a custom entrypoint shell script that reconfigures DSE cassandra.yaml and dse.yaml on startup to write data outside of /var/lib. This allows committing filled docker image - this issue can be closed.
