### ISSUE TITLE
Please install sudo on dse-server 5.1 image

### ISSUE THREAD

**Issue by varun-da** [datastax/docker-images#47]
Hi,

This will help tremendously in troubleshooting issues. Programs like less and netstat are not installed. And it is getting harder to debug the system when things are not working or things go wrong. Having some useful programs installed or sudo instead will help tremendously.

https://github.com/datastax/docker-images/blob/master/server/5.1/Dockerfile#L30

sudo is installed in 6.0 image https://github.com/datastax/docker-images/blob/master/server/6.0/Dockerfile#L29

I would like to avoid creating and maintaining my own docker image.

Thanks!

**Comment by roberd13** [comment]
@varun-da even though sudo is installed in 6.0.x it is not configured and there is not a password set for the dse user.   if you want to install other applications log into your container as root `docker exec -it --user root <container_name> bash` and use `apt install`
