### ISSUE TITLE
The dstat command seems missing in ubuntu linux image for datastax/dse-server:6.8.5-1

### ISSUE THREAD

**Issue by nadirdbit** [datastax/docker-images#81]
PS > docker exec -it my-dse dstat
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"dstat\": executable file not found in $PATH": unknown

Commands below were run:
docker pull datastax/dse-server:6.8.5-1
docker run -e DS_LICENSE=accept --name my-dse -d datastax/dse-server:6.8.5-1 -s -k -g

Thank you.

**Comment by mjkeeney** [comment]
Dstat is missing here by design.  You can build your own image to include dstat:

https://github.com/datastax/docker-images#building

**Comment by nadirdbit** [comment]
Hi Michael,

Unfortunately, this answer is not satisfactory - please arrange for a newer base image to include this tool and let me know when available so that I may download and use that instead of current version.

Thank you.

**Comment by mjkeeney** [comment]
Hi Nadir, I've gotten some further detail on this.  Dstat, along with many other tools, has been left out due to container size and cost of maintenance.  Our containers have been made public for exactly this reason, so you can add and customize as you wish. Please customize the container to fit your needs, and let us know if you run in to issues doing so.

Thanks
Mike

**Comment by nadirdbit** [comment]
Hi Michael,

Sorry - this reply just doesn't continue to make sense. I'd like to get a list of these tools which are considered helpful but non-core.

The dstat utility has already been discussed in an academy course and therefore surprised that it isn't included in your standard build.

Thank you.

**Comment by mjkeeney** [comment]
Hi Nadir, we don't have a list like that readily available.  Please do move forward with customizing our public containers as needed, and be assured that we will support containers post-modification.

**Comment by nadirdbit** [comment]
Hi Michael,

Okay - please arrange to provide a set of steps for the dstat tool inclusion in current build so that it can be attempted in current docker image.

Thank you.

**Comment by mjkeeney** [comment]
Sure thing.  I'll follow up with you tomorrow on steps to include dstat in the image build, Nadir

**Comment by roberd13** [comment]
Hi Nadir

The DataStax images were designed as a vanilla image for most users.  We built these images with as minimal size as we could, which mean minimal tools as possible.  That is why with regards to tools,  what user A wants may not be what user B wants or even user C and if we install everything that users A+B+C want = a bloated version of an already large without any extra tools.   We knew we could not satisfy every user, so we open sourced the docker images.  This allows you to easily customize it how you want.  If you want dstast, a specific version of java, a specific version of opscenter agent running on your image or any other combo that you want you have that option.  

Building the image with dstat is really simple.  Just modify the base image and build with the instructions @mjkeeney provided.  I myself have customized the DSE images many times to give myself specific configs I wanted for troubleshooting a specific issue.  I have even installed tools on the fly to troubleshoot issues. You can do this by logging in as root to your container and install dstat.

`docker exec -it --user root <container_name> bash` then run `apt install dstat` 

You now have a container running with the tool dstat.  You could then go as far as to run `docker commit <container_id> <somerepo:tag` and you will have yourself an image with dstat installed that you can run everytime you create a container and will have dstat.  

The options are endless

**Comment by mjkeeney** [comment]
Hi Nadir, as discussed on the call please provide the exact steps you too to install dstat, and the error message you received.  From there we can provide proper, specific steps for you

**Comment by roberd13** [comment]
@nadirdbit you will need to run as root `apt update` prior to running `apt install dstat`

**Comment by nadirdbit** [comment]
Hi Donnie,

Greatly appreciate your comments - this is resolved now.

Thank you.
