### ISSUE TITLE
Excessively long time to return results of "nodetool version" command

### ISSUE THREAD

**Issue by nadirdbit** [datastax/docker-images#83]
Hi,

This doesn't appear to be a direct docker issue but reporting this since command takes 1.5 minutes to return DSE and Cassandra release levels - seems excessively long even for a single node. 

Please investigate in case there is any performance bottleneck preventing it from completing quicker in larger configurations as unclear why it should take a minute of system time to obtain this simple output:

dse@6cf6ab586cd6:~$ time nodetool version
	DSE version: 6.8.5
	ReleaseVersion: 4.0.0.685

	real    1m27.842s
	user    0m34.102s
	sys     0m58.925s

Thank you.

**Comment by phact** [comment]
Would you mind sharing the specs on your machine?

**Comment by JeremiahDJordan** [comment]
The nodetool command has to load up its code in a JVM and connect to the running dse server over JMX, run some code on the server, and then return.  I would guess the issue here is related to resources available to your docker container being in contention.

**Comment by nadirdbit** [comment]
Hi All,

Not suspecting any bottleneck on my laptop and requisite information attached.

Both time components seem excessive - system and user. Believe each of these version details are being read from some configuration files.

If you would like to receive some trace output or other diagnostic information, then I can forward that for your analysis.

Thank you.

![system-info-20201120](https://user-images.githubusercontent.com/66740875/99855780-2fd69400-2b4d-11eb-84a9-405e6ec00a16.JPG)
![win-ver-20201120](https://user-images.githubusercontent.com/66740875/99855784-3107c100-2b4d-11eb-946b-56996936f98a.JPG)
![docker-ver-20201120](https://user-images.githubusercontent.com/66740875/99855785-3107c100-2b4d-11eb-92e1-c796c96b6de7.JPG)

**Comment by nadirdbit** [comment]
The slowness seems to have been caused by some resource contention
