### ISSUE TITLE
Authentication issue.

### ISSUE THREAD

**Issue by cyberliem** [datastax/docker-images#9]
Hi, I tried to access the cqlsh by normal uper user to the docker as follow:
`sudo docker exec -it my-dse cqlsh localhost -u cassandra -p casssandra
`
Then create another super user:

```
CREATE USER cyberliem WITH PASSWORD 'some password' SUPERUSER;
Unauthorized: Error from server: code=2100 [Unauthorized] message="Only superusers can create a role with superuser status
```

In addition, i found out that I can't modify the /opt/resources/cassandra/conf/cassandra.yaml to enable password Authentication.

**Comment by roberd13** [comment]
Cyberliem
You cannot add any `SUPERUSER` until you have authentication enabled even if you use the `-u cassandra -p casssandra` The best way to modify config files is to use the exposed [/conf volume](https://github.com/datastax/docker-images/blob/master/README.md#using-the-dse-conf-volume) or the [exposed volumes](https://github.com/datastax/docker-images#volumes-and-data) and copy your own config files " This is the true Docker Way".  If you really want to modify the logs at the container level you can login to your container as root to install your favorite editor with `apt-get` using this command `docker exec -it --user root $(containername) /bin/bash`

**Comment by roberd13** [comment]
@cyberliem were you able to enable security and add a new SUPERUSER?

**Comment by cyberliem** [comment]
Hi, I switched my deployment to traditional way. Will try to rewrite the docker file to let user define their supper user before deployment later.
